services:
  - name: gk-app-server
    type: web
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    repo: https://github.com/gkfat/gk-app/server
    branch: master

  - name: gk-app-client
    type: web
    plan: free
    runtime: docker
    repo: https://github.com/gkfat/gk-app/client
    branch: master

  - name: redis
    type: redis
    plan: free
    ipAllowList: []

databases:
  - name: db
    plan: free
    ipAllowList: []