services:
  - type: web
    name: gk-app-server
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    repo: https://github.com/gkfat/gk-app
    branch: master
    envVars:
      NODE_ENV: production

  - type: web
    name: gk-app-client
    env: static
    plan: free
    buildCommand: pnpm install && pnpm run build
    publishDir: client/dist
    repo: https://github.com/gkfat/gk-app
    branch: master