services:
  - name: gk-app-server
    type: web
    runtime: node
    plan: free
    rootDir: server
    buildCommand: pnpm install && pnpm build && pnpm seed
    startCommand: pnpm start
    repo: https://github.com/gkfat/gk-app.git
    branch: master
    healthCheckPath: /api/v1/health
    envVars:
      - fromGroup: gk-app-env-group

  - name: gk-app-client
    type: web
    plan: free
    rootDir: client
    runtime: static
    buildCommand: pnpm install && pnpm prod
    repo: https://github.com/gkfat/gk-app.git
    branch: master
    healthCheckPath: /

  - name: redis
    type: redis
    plan: free
    ipAllowList: [{ source: '0.0.0.0/0' }]

databases:
  - name: db
    plan: free
    ipAllowList: [{ source: '0.0.0.0/0' }]