services:
  db:
    image: postgres:latest
    container_name: got2do-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - got2do-network
      
  redis:
    image: redis:latest
    container_name: got2do-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - got2do-network

networks:
  got2do-network:
    driver: bridge

volumes:
  db_data: